name: Contexto
run-name: ¡Estoy aprendiendo a usar Contextos!
on: push
jobs:
  check-master:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"